'use strict';
// Add delivered files to ART_MANIFEST; unlisted files use procedural fallbacks.
RWB.ART_MANIFEST = [];
// Logical keys are stable; all request versioning is owned by assets.js.
RWB.ART_FILES = {
  "stage1-far": "assets/art/stage1-far.jpeg",
  "stage1-mid": "assets/art/stage1-mid.png",
  "stage1-near": "assets/art/stage1-near.png",
  "floor1": "assets/art/floor1.jpeg",
  "stage2-far": "assets/art/stage2-far.jpeg",
  "stage2-mid": "assets/art/stage2-mid.png",
  "stage2-near": "assets/art/stage2-near.png",
  "floor2": "assets/art/floor2.jpeg",
  "stage3-far": "assets/art/stage3-far.jpeg",
  "stage3-mid": "assets/art/stage3-mid.png",
  "stage3-near": "assets/art/stage3-near.png",
  "floor3": "assets/art/floor3.jpeg",
  "stage4-far": "assets/art/stage4-far.jpeg",
  "stage4-mid": "assets/art/stage4-mid.png",
  "stage4-near": "assets/art/stage4-near.png",
  "floor4": "assets/art/floor4.jpeg",
  "stage5-far": "assets/art/stage5-far.jpeg",
  "stage5-mid": "assets/art/stage5-mid.png",
  "stage5-near": "assets/art/stage5-near.png",
  "floor5": "assets/art/floor5.jpeg",
  "portrait-riley": "assets/art/portrait-riley.png",
  "portrait-twinkle": "assets/art/portrait-twinkle.png",
  "portrait-moiraine": "assets/art/portrait-moiraine.png",
  "portrait-loial": "assets/art/portrait-loial.png",
  "portrait-taim": "assets/art/portrait-taim.png",
  "portrait-fade": "assets/art/portrait-fade.png",
  "portrait-draghkar": "assets/art/portrait-draghkar.png",
  "portrait-forsaken": "assets/art/portrait-forsaken.png",
  "cg-riley": "assets/art/cg-riley.png",
  "cg-twinkle": "assets/art/cg-twinkle.png",
  "cg-trolloc": "assets/art/cg-trolloc.png",
  "cg-trolloc-chieftain": "assets/art/cg-trolloc-chieftain.png",
  "cg-darkfriend": "assets/art/cg-darkfriend.png",
  "cg-fade": "assets/art/cg-fade.png",
  "cg-cultist": "assets/art/cg-cultist.png",
  "cg-draghkar": "assets/art/cg-draghkar.png",
  "cg-stone-guard": "assets/art/cg-stone-guard.png",
  "cg-forsaken": "assets/art/cg-forsaken.png",
  "cg-turned-ashaman": "assets/art/cg-turned-ashaman.png",
  "cg-taim": "assets/art/cg-taim.png",
  "cg-loial": "assets/art/cg-loial.png",
  "cut-opening-01": "assets/cutscenes/cut-opening-01.jpeg",
  "cut-opening-02-v2": "assets/cutscenes/cut-opening-02-v2.jpeg",
  "cut-opening-03-v2": "assets/cutscenes/cut-opening-03-v2.jpeg",
  "cut-opening-04": "assets/cutscenes/cut-opening-04.jpeg",
  "cut-stage1": "assets/cutscenes/cut-stage1.jpeg",
  "cut-stage2": "assets/cutscenes/cut-stage2.jpeg",
  "cut-stage3": "assets/cutscenes/cut-stage3.jpeg",
  "cut-stage4": "assets/cutscenes/cut-stage4.jpeg",
  "cut-stage5-finale": "assets/cutscenes/cut-stage5-finale.jpeg",
  "cut-homecoming": "assets/cutscenes/cut-homecoming.jpeg",
  "logo": "assets/art/logo.png"
};
