'use strict';
// Add delivered files to ART_MANIFEST; unlisted files use procedural fallbacks.
RWB.ART_MANIFEST = [
  "assets/art/rig-riley.png",
  "assets/art/rig-twinkle.png",
  "assets/art/riley16-v2/frames.json",
  "assets/art/belal/idle.png",
  "assets/art/belal/walk1.png",
  "assets/art/belal/walk2.png",
  "assets/art/belal/walk3.png",
  "assets/art/belal/walk4.png",
  "assets/art/belal/windup.png",
  "assets/art/belal/slash.png",
  "assets/art/belal/lunge.png",
  "assets/art/belal/hurt.png",
  "assets/art/belal/cast.png",
  "assets/art/belal/portrait.png",
  "assets/art/riley16-v2/idle.png",
  "assets/art/riley16-v2/walk1.png",
  "assets/art/riley16-v2/walk2.png",
  "assets/art/riley16-v2/walk3.png",
  "assets/art/riley16-v2/walk4.png",
  "assets/art/riley16-v2/walk5.png",
  "assets/art/riley16-v2/walk6.png",
  "assets/art/riley16-v2/walk7.png",
  "assets/art/riley16-v2/walk8.png",
  "assets/art/riley16-v2/punch.png",
  "assets/art/riley16-v2/kick.png",
  "assets/art/riley16-v2/fireball.png",
  "assets/art/riley16-v2/hurt.png",
  "assets/art/riley16-v2/jump.png",
  "assets/art/riley16-v2/roundhouse.png",
  "assets/art/riley16-v2/knee.png",
  "assets/art/riley16-v2/channel.png",
  "assets/art/riley16-v2/lying.png",
  "assets/art/riley16-v2/getup.png",
  "assets/art/riley16/portrait.png",
  "assets/art/cg-cultist.png",
  "assets/art/cg-darkfriend.png",
  "assets/art/cg-draghkar.png",
  "assets/art/cg-fade.png",
  "assets/art/cg-forsaken.png",
  "assets/art/cg-loial.png",
  "assets/art/cg-stone-guard.png",
  "assets/art/cg-taim.png",
  "assets/art/cg-trolloc-chieftain.png",
  "assets/art/cg-trolloc.png",
  "assets/art/cg-turned-ashaman.png",
  "assets/art/floor-roof-loop.jpeg",
  "assets/art/floor1-loop.jpeg",
  "assets/art/floor2-loop.jpeg",
  "assets/art/floor3-loop.jpeg",
  "assets/art/floor4-loop.jpeg",
  "assets/art/floor5-loop.jpeg",
  "assets/art/logo.png",
  "assets/art/portrait-loial.png",
  "assets/art/portrait-moiraine.png",
  "assets/art/portrait-riley.png",
  "assets/art/portrait-taim.png",
  "assets/art/portrait-fade.png",
  "assets/art/portrait-draghkar.png",
  "assets/art/portrait-twinkle.png",
  "assets/art/riley-sheet.jpeg",
  "assets/art/stage1-far.jpeg",
  "assets/art/stage1-mid.png",
  "assets/art/stage1-mid-b.webp",
  "assets/art/stage1-mid-c.webp",
  "assets/art/stage1-near.png",
  "assets/art/stage2-far.jpeg",
  "assets/art/stage2-mid.png",
  "assets/art/stage2-mid-b.webp",
  "assets/art/stage2-mid-c.webp",
  "assets/art/stage2-near.png",
  "assets/art/stage3-far.jpeg",
  "assets/art/stage3-mid.png",
  "assets/art/stage3-mid-b.webp",
  "assets/art/stage3-mid-c.webp",
  "assets/art/stage3-near.png",
  "assets/art/stage4-far.jpeg",
  "assets/art/stage4-mid-cont.webp",
  "assets/art/stage4-near.png",
  "assets/art/stage5-far.jpeg",
  "assets/art/stage5-mid-cont.webp",
  "assets/art/stage5-roof-mid.webp",
  "assets/art/stage5-near.png",
  "assets/art/stage5-roof-far.jpeg",
  "assets/art/title-key.jpeg",
  "assets/art/twinkle-sheet.jpeg",
  "assets/cutscenes/cut-homecoming.jpeg",
  "assets/cutscenes/cut-escape.jpeg",
  "assets/cutscenes/cut-opening-01.jpeg",
  "assets/cutscenes/cut-opening-02-v2.jpeg",
  "assets/cutscenes/cut-opening-03-v2.jpeg",
  "assets/cutscenes/cut-opening-04.jpeg",
  "assets/cutscenes/cut-stage1.jpeg",
  "assets/cutscenes/cut-stage2.jpeg",
  "assets/cutscenes/cut-stage3.jpeg",
  "assets/cutscenes/cut-stage4.jpeg",
  "assets/cutscenes/cut-stage5-finale.jpeg",
  "assets/cutscenes/cut-stage5-arrival.jpeg",
  "assets/cutscenes/cut-callandor.jpeg"
];
// Logical keys are stable; all request versioning is owned by assets.js.
RWB.ART_FILES = {
  "riley16-frames": "assets/art/riley16-v2/frames.json",
  "belal-idle": "assets/art/belal/idle.png",
  "belal-walk1": "assets/art/belal/walk1.png",
  "belal-walk2": "assets/art/belal/walk2.png",
  "belal-walk3": "assets/art/belal/walk3.png",
  "belal-walk4": "assets/art/belal/walk4.png",
  "belal-windup": "assets/art/belal/windup.png",
  "belal-slash": "assets/art/belal/slash.png",
  "belal-lunge": "assets/art/belal/lunge.png",
  "belal-hurt": "assets/art/belal/hurt.png",
  "belal-cast": "assets/art/belal/cast.png",
  "belal-portrait": "assets/art/belal/portrait.png",
  "riley16-idle": "assets/art/riley16-v2/idle.png",
  "riley16-walk1": "assets/art/riley16-v2/walk1.png",
  "riley16-walk2": "assets/art/riley16-v2/walk2.png",
  "riley16-walk3": "assets/art/riley16-v2/walk3.png",
  "riley16-walk4": "assets/art/riley16-v2/walk4.png",
  "riley16-walk5": "assets/art/riley16-v2/walk5.png",
  "riley16-walk6": "assets/art/riley16-v2/walk6.png",
  "riley16-walk7": "assets/art/riley16-v2/walk7.png",
  "riley16-walk8": "assets/art/riley16-v2/walk8.png",
  "riley16-punch": "assets/art/riley16-v2/punch.png",
  "riley16-kick": "assets/art/riley16-v2/kick.png",
  "riley16-fireball": "assets/art/riley16-v2/fireball.png",
  "riley16-hurt": "assets/art/riley16-v2/hurt.png",
  "riley16-jump": "assets/art/riley16-v2/jump.png",
  "riley16-roundhouse": "assets/art/riley16-v2/roundhouse.png",
  "riley16-knee": "assets/art/riley16-v2/knee.png",
  "riley16-channel": "assets/art/riley16-v2/channel.png",
  "riley16-lying": "assets/art/riley16-v2/lying.png",
  "riley16-getup": "assets/art/riley16-v2/getup.png",
  "riley16-portrait": "assets/art/riley16/portrait.png",
  "rig-riley": "assets/art/rig-riley.png",
  "rig-twinkle": "assets/art/rig-twinkle.png",
  "stage1-far": "assets/art/stage1-far.jpeg",
  "stage1-mid": "assets/art/stage1-mid.png",
  "stage1-mid-b": "assets/art/stage1-mid-b.webp",
  "stage1-mid-c": "assets/art/stage1-mid-c.webp",
  "stage1-near": "assets/art/stage1-near.png",
  "floor1": "assets/art/floor1-loop.jpeg",
  "stage2-far": "assets/art/stage2-far.jpeg",
  "stage2-mid": "assets/art/stage2-mid.png",
  "stage2-mid-b": "assets/art/stage2-mid-b.webp",
  "stage2-mid-c": "assets/art/stage2-mid-c.webp",
  "stage2-near": "assets/art/stage2-near.png",
  "floor2": "assets/art/floor2-loop.jpeg",
  "stage3-far": "assets/art/stage3-far.jpeg",
  "stage3-mid": "assets/art/stage3-mid.png",
  "stage3-mid-b": "assets/art/stage3-mid-b.webp",
  "stage3-mid-c": "assets/art/stage3-mid-c.webp",
  "stage3-near": "assets/art/stage3-near.png",
  "floor3": "assets/art/floor3-loop.jpeg",
  "stage4-far": "assets/art/stage4-far.jpeg",
  "stage4-mid-cont": "assets/art/stage4-mid-cont.webp",
  "stage4-mid": "assets/art/stage4-mid.png",
  "stage4-mid-b": "assets/art/stage4-mid-b.webp",
  "stage4-transition-bc": "assets/art/stage4-transition-bc.webp",
  "stage4-mid-c": "assets/art/stage4-mid-c.webp",
  "stage4-near": "assets/art/stage4-near.png",
  "floor4": "assets/art/floor4-loop.jpeg",
  "stage5-far": "assets/art/stage5-far.jpeg",
  "stage5-mid-cont": "assets/art/stage5-mid-cont.webp",
  "stage5-mid": "assets/art/stage5-mid.png",
  "stage5-mid-b": "assets/art/stage5-mid-b.webp",
  "stage5-transition-ab": "assets/art/stage5-transition-ab.webp",
  "stage5-roof-mid": "assets/art/stage5-roof-mid.webp",
  "stage5-near": "assets/art/stage5-near.png",
  "floor5": "assets/art/floor5-loop.jpeg",
  "portrait-riley": "assets/art/riley16/portrait.png",
  "portrait-riley-legacy": "assets/art/portrait-riley.png",
  "portrait-twinkle": "assets/art/portrait-twinkle.png",
  "portrait-moiraine": "assets/art/portrait-moiraine.png",
  "portrait-loial": "assets/art/portrait-loial.png",
  "portrait-taim": "assets/art/portrait-taim.png",
  "portrait-fade": "assets/art/portrait-fade.png",
  "portrait-draghkar": "assets/art/portrait-draghkar.png",
  "portrait-forsaken": "assets/art/belal/portrait.png",
  "cg-riley": "assets/art/cg-riley.png",
  "cg-twinkle": "assets/art/cg-twinkle.png",
  "cg-trolloc": "assets/art/cg-trolloc.png",
  "cg-trolloc-chieftain": "assets/art/cg-trolloc-chieftain.png",
  "cg-darkfriend": "assets/art/cg-darkfriend.png",
  "cg-fade": "assets/art/cg-fade.png",
  "cg-cultist": "assets/art/cg-cultist.png",
  "cg-draghkar": "assets/art/cg-draghkar.png",
  "cg-stone-guard": "assets/art/cg-stone-guard.png",
  "cg-forsaken": "assets/art/cg-forsaken.png",
  "cg-turned-ashaman": "assets/art/cg-turned-ashaman.png",
  "cg-taim": "assets/art/cg-taim.png",
  "cg-loial": "assets/art/cg-loial.png",
  "cut-opening-01": "assets/cutscenes/cut-opening-01.jpeg",
  "cut-opening-02-v2": "assets/cutscenes/cut-opening-02-v2.jpeg",
  "cut-opening-03-v2": "assets/cutscenes/cut-opening-03-v2.jpeg",
  "cut-opening-04": "assets/cutscenes/cut-opening-04.jpeg",
  "cut-stage1": "assets/cutscenes/cut-stage1.jpeg",
  "cut-stage2": "assets/cutscenes/cut-stage2.jpeg",
  "cut-stage3": "assets/cutscenes/cut-stage3.jpeg",
  "cut-stage4": "assets/cutscenes/cut-stage4.jpeg",
  "cut-stage5-finale": "assets/cutscenes/cut-stage5-finale.jpeg",
  "cut-stage5-arrival": "assets/cutscenes/cut-stage5-arrival.jpeg",
  "cut-callandor": "assets/cutscenes/cut-callandor.jpeg",
  "cut-homecoming": "assets/cutscenes/cut-homecoming.jpeg",
  "cut-escape": "assets/cutscenes/cut-escape.jpeg",
  "title-key": "assets/art/title-key.jpeg",
  "riley-sheet": "assets/art/riley-sheet.jpeg",
  "twinkle-sheet": "assets/art/twinkle-sheet.jpeg",
  "stage5-roof-far": "assets/art/stage5-roof-far.jpeg",
  "floor-roof": "assets/art/floor-roof-loop.jpeg",
  "logo": "assets/art/logo.png"
};
