'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('node:assert/strict'),crypto=require('crypto'),{createRequire}=require('module');
const {root,runtime}=require('../runtime.cjs');
const req=createRequire(root+'/tools/soak.cjs'),{boot}=req(root+'/tools/soak.cjs'),{createCanvas,Image}=req('@napi-rs/canvas');
const tick=()=>new Promise(r=>setImmediate(r)),rows=[];
async function engine(variant,images,kind,scale){const R=boot(root);await tick();R.assets.get=k=>images.get(k)||null;R.assets.has=k=>images.has(k);R.display.renderScale=scale;let time=0,allocations=0;const screen=createCanvas(640,360),context={window:{RWB:R},document:{createElement:()=>{allocations++;return createCanvas(1,1);},getElementById:()=>screen},performance:{now:()=>time+=.01},console};vm.createContext(context);vm.runInContext(runtime(variant,'performance.js'),context);vm.runInContext(runtime(variant,'puppets.js').replace('R.Puppet={defs,','R.Puppet={test:{getRig},defs,'),context);const rig=R.Puppet.test.getRig(R.Puppet.defs[kind]);return {R,rig,allocations:()=>allocations,run(key){R.Puppet.wantPose(kind,key,2);const job=R.Bake.q[0];let slices=0;while(R.Bake.q.length&&slices++<2000){R.Bake.pump(4);if(R.Bake.q.length)assert.ok(!rig.library?.has(key),'partial pose cannot be published');}assert.equal(R.Bake.q.length,0);assert.equal(job.state.vertices,null);return rig.library.get(key);},drop(){R.Bake.touches.length=0;for(const e of rig.library?.values()||[])e.surface.width=e.surface.height=1;rig.library?.clear();}};}
const rgba=(entry,facing)=>{const c=createCanvas(entry.surface.width,entry.surface.height),g=c.getContext('2d');if(facing<0){g.translate(c.width,0);g.scale(-1,1);}g.drawImage(entry.surface,0,0);const data=Buffer.from(g.getImageData(0,0,c.width,c.height).data);c.width=c.height=1;return data;};
(async()=>{const seed=boot(root);await tick();const kinds=Object.keys(seed.Puppet.defs).filter(k=>k!=='forsaken'),images=new Map();for(const kind of kinds){const key=seed.Puppet.defs[kind].key;if(images.has(key))continue;const im=new Image();im.src=fs.readFileSync(path.join(root,seed.ART_FILES[key]));await im.decode();images.set(key,im);}const keys=['idle','hurt','cast','attack','air','channel',...Array.from({length:12},(_,i)=>'w'+i),...Array.from({length:6},(_,i)=>'k'+i)];let comparisons=0,identity=0,transformed=0;
for(const kind of kinds)for(const scale of [1,2,3]){const control=await engine('control',images,kind,scale),candidate=await engine('candidate',images,kind,scale);for(const key of keys){const ac=control.allocations(),bc=candidate.allocations(),a=control.run(key),b=candidate.run(key);assert.deepEqual(JSON.parse(JSON.stringify(a.bounds)),JSON.parse(JSON.stringify(b.bounds)));assert.equal(a.scale,b.scale);assert.equal(a.identity,b.identity);assert.equal(control.allocations()-ac,candidate.allocations()-bc,'no additional canvas allocation');for(const facing of [-1,1]){const ap=rgba(a,facing),bp=rgba(b,facing);assert.ok(ap.equals(bp),[kind,scale,key,facing].join('/')+' changed pixels');const ah=crypto.createHash('sha256').update(ap).digest('hex'),bh=crypto.createHash('sha256').update(bp).digest('hex');assert.equal(ah,bh);rows.push({kind,scale,key,facing,width:a.surface.width,height:a.surface.height,bounds:JSON.parse(JSON.stringify(a.bounds)),identity:!!a.identity,controlHash:ah,candidateHash:bh,exact:true});comparisons++;if(b.identity)identity++;else transformed++;}control.drop();candidate.drop();}control.rig.texture.width=control.rig.texture.height=candidate.rig.texture.width=candidate.rig.texture.height=1;console.log('PASS '+kind+' '+scale+'x exact queued pixels');}
const report={method:'Offline decoded Node Skia, actual combined Bake scheduler and renderer versus original baseline, ten runtime mesh rigs, 24 poses, scales 1/2/3, both facings. Unchanged RGBA hashes/bounds/scales, no partial publication, equal canvas allocations and completed snapshot release. Synthetic yield clock; no performance inference. Forsaken uses separate runtime sprites and is not a mesh-rendered character.',comparisons,identity,transformed,allExact:true,rows};fs.writeFileSync(__dirname+'/pixel-report.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({comparisons,identity,transformed,allExact:true}));})().catch(e=>{console.error(e);process.exitCode=1;});
