'use strict';
// Offline correctness only. Actual decoded assets/render code with controlled
// Promise readiness; a deterministic clock is deliberately not native timing.
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('node:assert/strict'),crypto=require('crypto'),{createRequire}=require('module');
const {root,runtime}=require('../runtime.cjs');
const req=createRequire(root+'/tools/soak.cjs'),{boot}=req(root+'/tools/soak.cjs'),{createCanvas,Image}=req('@napi-rs/canvas');
const files=variant=>({perf:runtime(variant,'performance.js'),puppets:runtime(variant,'puppets.js')});
const sources={control:files('control'),candidate:files('candidate')},rows=[];
const tick=()=>new Promise(r=>setImmediate(r));
function basic(source){let time=0;const R={perf:{},display:{}},context={window:{RWB:R},performance:{now:()=>time},console};vm.createContext(context);vm.runInContext(source,context);return {R,set:v=>time=v,advance:v=>time+=v,now:()=>time};}
function record(name,data){rows.push({name,pass:true,...JSON.parse(JSON.stringify(data))});console.log('PASS '+name);}
function unitTests(){
  for(const [variant,source] of Object.entries(sources)){
    {const {R}=basic(source.perf),calls=[];const a=R.Bake.enqueue(2,'older',()=>{calls.push('older');return true;}),b=R.Bake.enqueue(3,'demand',()=>{calls.push('demand');return true;});const seq=b.seq;assert.equal(R.Bake.enqueue(0,'demand',()=>{throw Error('must retain run');}),b);assert.equal(b.seq,seq);R.Bake.pump(4);assert.deepEqual(calls,['demand','older']);assert.equal(R.Bake.names.size,0);record(variant+': demand promotes existing job and keeps sequence',{});}
    {const {R}=basic(source.perf);let calls=0;R.Bake.enqueue(0,'zero',()=>{calls++;return true;});R.Bake.pump(0);R.Bake.pump(-1);assert.equal(calls,0);assert.equal(R.perf.inBake,false);record(variant+': nonpositive deadline admits no work',{});}
    {const c=basic(source.perf),{R}=c,calls=[],ends=[];for(let i=0;i<5;i++)R.Bake.enqueue(i,''+i,(job,end)=>{calls.push(c.now());ends.push(end);c.advance(1.5);return true;});R.Bake.pump(4);assert.deepEqual(calls,[0,1.5,3]);assert.deepEqual(ends,[4,4,4]);assert.equal(R.Bake.q.length,2);assert.equal(R.perf.lastPumpMs,4.5);record(variant+': unchanged 4 ms cooperative deadline',{starts:calls,end:4,atomicOverrun:0.5});}
    {const {R}=basic(source.perf);let calls=0;for(let i=0;i<100;i++)R.Bake.enqueue(1,''+i,()=>{calls++;return true;});R.Bake.pump(4);assert.equal(calls,64);assert.equal(R.Bake.q.length,36);record(variant+': runnable guard remains 64',{calls});}
    {const c=basic(source.perf),{R}=c,calls=[];R.Bake.enqueue(0,'fast-runnable',()=>{calls.push('head');c.advance(.02);return false;});R.Bake.enqueue(1,'tail',()=>{calls.push('tail');return true;});R.Bake.pump(4);assert.deepEqual(calls,['head']);record(variant+': fast runnable work is never mistaken for dependency blocking',{});}
  }
  {const {R}=basic(sources.candidate.perf),calls=[];for(let i=0;i<130;i++)R.Bake.enqueue(0,'blocked'+i,j=>{calls.push(j.name);j.ready=()=>false;return false;});R.Bake.enqueue(3,'ready-tail',j=>{calls.push(j.name);return true;});R.Bake.pump(4);assert.equal(calls.length,131);assert.equal(new Set(calls).size,131);assert.equal(calls.at(-1),'ready-tail');assert.equal(R.Bake.q.length,130);calls.length=0;R.Bake.pump(4);assert.equal(calls.length,0);record('candidate: 130 blocked jobs cannot starve ready tail; all-blocked exit finite',{blocked:130,firstPumpCalls:131,secondPumpCalls:0});}
  {const {R}=basic(sources.candidate.perf),calls=[];for(const [name,pri,blocked] of [['blocked0',0,true],['old',2,false],['blocked1',1,true],['new',2,false],['urgent',1,false],['last',2,false]])R.Bake.enqueue(pri,name,j=>{calls.push(name);j.ready=()=>!blocked;return !blocked;});R.Bake.pump(4);assert.deepEqual(calls.filter(n=>!n.startsWith('blocked')),['urgent','old','new','last']);assert.deepEqual(Array.from(R.Bake.q,j=>j.name),['blocked0','blocked1']);record('candidate: runnable priority and stable FIFO survive blocked interleaving',{calls});}
  {const c=basic(sources.candidate.perf),{R}=c,calls=[];R.Bake.enqueue(0,'blocked',j=>{calls.push('blocked');j.ready=()=>false;c.advance(4);return false;});R.Bake.enqueue(1,'tail',()=>{calls.push('tail');return true;});R.Bake.pump(4);assert.deepEqual(calls,['blocked']);assert.equal(R.perf.lastPumpMs,4);record('candidate: blocked step exhausting deadline does not admit a tail',{});}
  {const c=basic(sources.candidate.perf),{R}=c;let ran=false;for(let i=0;i<10;i++)R.Bake.enqueue(i,'scan'+i,()=>{ran=true;return true;},{ready:()=>{c.advance(.6);return true;}});R.Bake.pump(4);assert.equal(ran,false);record('candidate: readiness scanning cannot start a job after the deadline',{});}
  {const {R}=basic(sources.candidate.perf),calls=[];let ready=false;R.Bake.enqueue(0,'head',j=>{calls.push('head');if(!ready){j.ready=()=>ready;return false;}return true;});R.Bake.enqueue(1,'release',()=>{calls.push('release');ready=true;return true;});R.Bake.enqueue(2,'tail',()=>{calls.push('tail');return true;});R.Bake.pump(4);assert.deepEqual(calls,['head','release','head','tail']);record('candidate: synchronous dependency release restores original priority in the same pump',{calls});}
  {const c=basic(sources.candidate.perf),{R}=c,calls=[];let ready=false;for(let i=0;i<60;i++)R.Bake.enqueue(0,'blocked'+i,j=>{calls.push(j.name);j.ready=()=>ready;c.advance(.2);return false;});R.Bake.enqueue(1,'tail',()=>{calls.push('tail');return true;});let pumps=0;while(R.Bake.names.has('tail')&&pumps++<8)R.Bake.pump(4);assert.ok(!R.Bake.names.has('tail'),'known blocked prefix cannot repeatedly exhaust later frames');assert.equal(calls.filter(n=>n==='tail').length,1);assert.equal(new Set(calls).size,calls.length);record('candidate: expensive blocked prefix cannot starve ready tail across deadlines',{blocked:60,initializationMs:.2,pumps,calls:calls.length});}
  {const {R}=basic(sources.candidate.perf),calls=[];const b=R.Bake.enqueue(0,'blocked',j=>{calls.push('blocked');j.ready=()=>false;return false;});R.Bake.pump(4);R.Bake.drop(j=>j===b);assert.ok(!R.Bake.names.has('blocked'));const replacement=R.Bake.enqueue(0,'blocked',j=>{calls.push('replacement');return true;});assert.notEqual(replacement,b);R.Bake.pump(4);assert.deepEqual(calls,['blocked','replacement']);record('candidate: cancellation and same-name replacement clear deduplication state',{});}
}
async function engine(source,images,clockStep=.000001){
  const R=boot(root);await tick();const available=new Map(images),pending=[];let time=0;
  R.assets.get=k=>available.get(k)||null;R.assets.has=k=>available.has(k);R.display.renderScale=2;
  const screen=createCanvas(640,360),context={window:{RWB:R},document:{createElement:()=>createCanvas(1,1),getElementById:()=>screen},performance:{now:()=>time+=clockStep},console,
    createImageBitmap(image,options){let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});pending.push({image,options,resolve,reject,closeCount:0});return promise;}};
  vm.createContext(context);vm.runInContext(source.perf,context);vm.runInContext(source.puppets.replace('R.Puppet={defs,','R.Puppet={test:{getRig,peekRig,stepPose,dropRig,building,actorFor},defs,'),context);
  const queue=(kind,key,pri)=>{R.Puppet.wantPose(kind,key,pri);const job=R.Bake.q.find(j=>j.kind===kind&&j.key===key);assert.ok(job);return job;};
  const settle=async(p,fail=false)=>{if(fail)p.reject(Error('controlled decode failure'));else{const c=createCanvas(p.options.resizeWidth,p.options.resizeHeight);c.getContext('2d').drawImage(p.image,0,0,c.width,c.height);c.close=()=>p.closeCount++;p.bitmap=c;p.resolve(c);}await tick();};
  const pump=(n=1)=>{for(let i=0;i<n;i++)R.Bake.pump(4);};
  const drain=()=>{for(let i=0;R.Bake.q.length&&i<3000;i++)pump();assert.equal(R.Bake.q.length,0,'finite completion');};
  return {R,available,pending,queue,pump,drain,settle,screen};
}
function hash(entry){assert.ok(entry?.surface);const c=entry.surface;return crypto.createHash('sha256').update(JSON.stringify({bounds:entry.bounds,scale:entry.scale,identity:!!entry.identity})).update(Buffer.from(c.getContext('2d').getImageData(0,0,c.width,c.height).data)).digest('hex');}
async function actualTests(images){
  const hashes={};
  for(const [variant,source] of Object.entries(sources)){
    const e=await engine(source,images),{R}=e,ready=R.Puppet.test.getRig(R.Puppet.defs.ashaman);
    const head=e.queue('loial','w0',0),tail=e.queue('ashaman','w3',2),attempts=[];
    for(const job of [head,tail]){const run=job.run;job.run=(...args)=>{attempts.push(job.kind);return run(...args);};}
    e.pump();assert.equal(e.pending.length,1);assert.ok(!R.Puppet.test.peekRig(R.Puppet.defs.loial));
    const tailReady=!!ready.library?.has('w3');assert.equal(tailReady,variant==='candidate');assert.equal(attempts.filter(k=>k==='loial').length,1);assert.ok(!head.rig?.library?.has('w0'));
    R.perf.poseFallbacks=0;R.Puppet.draw(e.screen.getContext('2d'),R.Puppet.test.actorFor(R.Puppet.defs.ashaman,'w3'),0,'ashaman');
    assert.equal(R.perf.poseFallbacks,variant==='candidate'?0:1);
    record(variant+': controlled unresolved bitmap head with decoded ready pose tail',{tailPublishedInFirstPump:tailReady,attempts,bitmapPending:true,oneControlledDrawFallbacks:R.perf.poseFallbacks});
    const pending=e.pending[0];await e.settle(pending);e.drain();assert.equal(pending.closeCount,1);assert.equal(head.state.vertices,null);assert.equal(tail.state.vertices,null);assert.ok(!head.ready);
    hashes[variant]={loial:hash(head.rig.library.get('w0')),ashaman:hash(ready.library.get('w3'))};
    record(variant+': async resolution resumes and closes bitmap exactly once',{closeCount:pending.closeCount,hashes:hashes[variant]});
  }
  assert.deepEqual(hashes.candidate,hashes.control);record('candidate/control: resolved poses remain byte-identical',{hashes:hashes.candidate});
  {const e=await engine(sources.candidate,images),{R}=e,jobs=[];for(const kind of ['loial','ashaman'])for(const key of ['w0','w3','hurt','cast'])jobs.push(e.queue(kind,key,0));const calls=new Map();for(const job of jobs){const run=job.run;job.run=(...args)=>{calls.set(job,(calls.get(job)||0)+1);return run(...args);};}e.pump();assert.equal(e.pending.length,2);assert.equal(calls.size,jobs.length);assert.ok([...calls.values()].every(n=>n===1));assert.ok(jobs.every(j=>j.ready&&!j.ready()&&!j.rig));record('candidate: shared pending rigs are attempted once per queued pose and publish nothing',{jobs:jobs.length,dependencies:e.pending.length});for(const p of e.pending)await e.settle(p);e.drain();assert.ok(e.pending.every(p=>p.closeCount===1));record('candidate: all previously blocked jobs eventually complete',{jobs:jobs.length});}
  {const e=await engine(sources.candidate,images),{R}=e;R.Puppet.test.getRig(R.Puppet.defs.ashaman);const a=e.queue('ashaman','w0',2),b=e.queue('ashaman','w3',3);e.queue('loial','w0',0);const bSeq=b.seq;R.Puppet.wantPose('ashaman','w3',0);assert.equal(b.seq,bSeq);assert.equal(b.pri,0);const complete=[];for(const j of [a,b]){const run=j.run;j.run=(...args)=>{const done=run(...args);if(done)complete.push(j.key);return done;};}e.pump();assert.deepEqual(complete,['w3','w0']);record('candidate: actual promoted demand pose finishes first among ready poses',{completion:complete,sequencePreserved:true});}
  const rejectedHashes={};for(const [variant,source] of Object.entries(sources)){const e=await engine(source,images);const j=e.queue('loial','hurt',0);e.pump();await e.settle(e.pending[0],true);e.drain();assert.ok(j.rig.library.has('hurt'));assert.equal(j.state.vertices,null);rejectedHashes[variant]=hash(j.rig.library.get('hurt'));record(variant+': rejected bitmap falls back to the original source and completes',{hash:rejectedHashes[variant]});}assert.equal(rejectedHashes.candidate,rejectedHashes.control);record('candidate/control: rejected-decode fallback output is byte-identical',{hash:rejectedHashes.control});
  {const e=await engine(sources.candidate,images),{R}=e;const j=e.queue('loial','w0',0);e.pump();const old=e.pending[0];R.Puppet.test.dropRig('loial');e.pump();assert.equal(e.pending.length,2,'removed building state wakes the retained queued job');const current=e.pending[1];await e.settle(old);e.pump();assert.ok(!j.rig,'old-state resolution cannot publish replacement rig');await e.settle(current);e.drain();assert.ok(j.rig.library.has('w0'));assert.equal(current.closeCount,1);assert.equal(old.closeCount,1);record('candidate: replacement rig dependency wakes and closes stale bitmap exactly once',{currentBitmapCloseCount:1,oldDetachedBitmapCloseCount:1});}

  for(const [variant,source] of Object.entries(sources)){
    {const e=await engine(source,images),{R}=e;const j=e.queue('loial','w0',0);e.pump();const p=e.pending[0];R.Puppet.test.dropRig('loial');R.Bake.drop(job=>job.kind==='loial');await e.settle(p);e.pump();assert.equal(R.Bake.q.length,0);assert.ok(!R.Bake.names.has(j.name));assert.ok(!R.Puppet.test.peekRig(R.Puppet.defs.loial));assert.equal(R.Puppet.test.building.size,0);assert.equal(p.closeCount,variant==='candidate'?1:0);record(variant+': dropped pending rig cannot resurrect or publish; combined candidate closes late bitmap once',{lateBitmapCloseCount:p.closeCount,limitation:'Close-count correctness only; no memory impact inferred.'});}
    {const e=await engine(source,images),{R}=e;const j=e.queue('loial','w0',0);e.pump();const p=e.pending[0];e.available.delete(R.Puppet.defs.loial.key);e.pump();assert.equal(R.Bake.q.length,0);assert.ok(!j.rig);await e.settle(p);e.pump();assert.equal(p.closeCount,0);assert.equal(R.Puppet.test.building.size,1);R.Puppet.test.dropRig('loial');assert.equal(R.Puppet.test.building.size,0);assert.equal(p.closeCount,variant==='candidate'?1:0);record(variant+': source asset release removes queued pose without publishing',{retainedBuildingStatesUntilDrop:1,lateBitmapCloseCountBeforeDrop:0,bitmapCloseCountAfterDrop:p.closeCount,limitation:'Cached building state retains resolved bitmap until drop/reuse; combined drop closes it once; no memory measurement.'});}
  }
}
module.exports={engine,root,req,tick,unitTests};
if(require.main===module)(async()=>{unitTests();const seed=boot(root);await tick();const images=new Map();for(const kind of ['loial','ashaman']){const key=seed.Puppet.defs[kind].key,image=new Image();image.src=fs.readFileSync(path.join(root,seed.ART_FILES[key]));await image.decode();images.set(key,image);}await actualTests(images);const report={method:'Offline actual decoded assets and actual ensureRig/stepPose/Bake, deterministically controlled createImageBitmap Promise completion. Synthetic clock checks ordering/liveness/deadlines, not performance.',checks:rows.length,allPassed:true,rows};fs.writeFileSync(__dirname+'/queue-report.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({checks:rows.length,allPassed:true}));})().catch(e=>{console.error(e);process.exitCode=1;});
