'use strict';
const {control:controlSource,candidate:candidateSource}=require('../runtime.cjs');
const{fs,assert,createCanvas,keys,hash,imagesFor,engine,rgba}=require('./harness.cjs');
(async()=>{const{images,kinds}=await imagesFor(),rows=[];let comparisons=0,identity=0,transformed=0,contacts=0,controlAllocated=0,poolAllocated=0;for(const kind of kinds)for(const scale of [1,2,3]){const control=await engine(controlSource('puppets.js'),images,kind,scale),variant=await engine(candidateSource('puppets.js'),images,kind,scale);for(const key of keys){const ac=control.stats().canvases,bc=variant.stats().canvases;
 // Poison every reused field. Skinning must overwrite the entire snapshot before
 // bounds, identity detection or raster reads it; there is no lazy old-pose data.
 for(const snapshot of variant.R.Puppet.test.pool(variant.rig)||[])for(const layer of snapshot)for(const v of layer){v.x=NaN;v.y=NaN;v.X=NaN;v.Y=NaN;}
 const a=control.run(key),b=variant.run(key);assert.deepEqual(JSON.parse(JSON.stringify(a.bounds)),JSON.parse(JSON.stringify(b.bounds)));assert.equal(a.scale,b.scale);assert.equal(a.identity,b.identity);assert.equal(control.stats().canvases-ac,variant.stats().canvases-bc,'no extra canvas allocation');assert.equal(variant.R.Puppet.test.pool(variant.rig).length,1,'sequential work retains exactly one snapshot');
 if(b.identity){const c=createCanvas(b.surface.width,b.surface.height),g=c.getContext('2d');g.setTransform(b.scale,0,0,b.scale,-b.bounds.left,-b.bounds.top);g.drawImage(variant.rig.texture,0,0,variant.rig.w,variant.rig.h);assert.ok(Buffer.from(c.getContext('2d').getImageData(0,0,c.width,c.height).data).equals(Buffer.from(b.surface.getContext('2d').getImageData(0,0,c.width,c.height).data)),'identity uses exact processed texture');c.width=c.height=1;}
 for(const facing of [-1,1]){assert.ok(rgba(a,facing).equals(rgba(b,facing)),[kind,scale,key,facing].join('/')+' exact RGBA');comparisons++;if(b.identity)identity++;else transformed++;}control.clean();variant.clean();}
 for(const facing of [-1,1])for(const state of ['idle','walk']){const actor={x:100,y:280,z:0,facing,state,stateT:0,gait:{moving:state==='walk',phase:.25,feet:[{x:102,y:280,lift:0,stance:true},{x:98,y:280,lift:4,stance:false}]}};assert.deepEqual(JSON.parse(JSON.stringify(control.R.Puppet.contacts(actor,kind))),JSON.parse(JSON.stringify(variant.R.Puppet.contacts(actor,kind))));contacts++;}
 const c=control.stats(),p=variant.stats();assert.equal(c.allocatedVertices,24*425);assert.equal(p.allocatedVertices,425);assert.equal(p.uniqueVertexObjects,425);controlAllocated+=c.allocatedVertices;poolAllocated+=p.allocatedVertices;rows.push({kind,scale,comparisons:48,control:c,pool:p,freeSnapshots:1});control.dispose();variant.dispose();console.log('PASS '+kind+' '+scale+'x exact reused queued pixels');}
 const negative=await engine(candidateSource('puppets.js'),images,'ashaman',2),t=negative.R.Puppet.test,d=negative.R.Puppet.defs.ashaman,r=negative.rig,a=t.actorFor(d,'idle'),neutral=negative.R.Puppet.pose(a,d.height),lean={...neutral,lean:Number.EPSILON},l=t.bakePose(r,t.targets(a,d,r,lean),lean);assert.equal(l.identity,false,'tiny real lean remains on mesh');const bones=t.targets(a,d,r,neutral);bones[0][0].x+=Number.EPSILON*r.w;const b=t.bakePose(r,bones,neutral);assert.equal(b.identity,false,'tiny bone deformation remains on mesh');negative.dispose();
 const report={method:'Decoded Node Skia; deterministic yield clock; actual combined candidate runtime with original baseline control. Full exact RGBA (including edge alpha), metadata, processed identity, contacts and poisoned reuse. No native FPS, cold, GC or physical-device claim.',controlHash:hash(fs.readFileSync(controlSource('puppets.js'))),candidateHash:hash(fs.readFileSync(candidateSource('puppets.js'))),comparisons,identity,transformed,contacts,negativeControls:2,controlAllocatedVertices:controlAllocated,poolAllocatedVertices:poolAllocated,allocationReduction:1-poolAllocated/controlAllocated,noAdditionalCanvases:true,rows};fs.writeFileSync(__dirname+'/pixel-report.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({...report,rows:undefined}));})().catch(e=>{console.error(e);process.exitCode=1;});
