'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('node:assert/strict'),crypto=require('crypto'),{createRequire}=require('module');
const {root,runtime,control,candidate}=require('../runtime.cjs');
const req=createRequire(root+'/tools/soak.cjs'),{boot}=req(root+'/tools/soak.cjs'),{createCanvas,Image}=req('@napi-rs/canvas');
const keys=['idle','hurt','cast','attack','air','channel',...Array.from({length:12},(_,i)=>'w'+i),...Array.from({length:6},(_,i)=>'k'+i)];
const hash=s=>crypto.createHash('sha256').update(s).digest('hex');
async function imagesFor(kinds){const R=boot(root);await new Promise(r=>setImmediate(r));const images=new Map();for(const kind of kinds||Object.keys(R.Puppet.defs).filter(k=>k!=='forsaken')){const key=R.Puppet.defs[kind].key;if(images.has(key))continue;const image=new Image();image.src=fs.readFileSync(path.join(root,R.ART_FILES[key]));await image.decode();images.set(key,image);}return{images,kinds:kinds||Object.keys(R.Puppet.defs).filter(k=>k!=='forsaken')};}
async function engine(file,images,kind,scale){const source=fs.readFileSync(file,'utf8'),R=boot(root);await new Promise(r=>setImmediate(r));R.assets.get=k=>images.get(k)||null;R.assets.has=k=>images.has(k);R.display.renderScale=scale;R.perf.fullFace=true;let time=0,canvases=0;const screen=createCanvas(640,360),context={window:{RWB:R},document:{createElement:()=>{canvases++;return createCanvas(1,1);},getElementById:()=>screen},performance:{now:()=>time+=.01},console};vm.createContext(context);vm.runInContext(runtime(file===control('puppets.js')?'control':'candidate','performance.js'),context);const extra=source.includes('const poseVertexPools=')?',pool:r=>poseVertexPools.get(r),releasePoseVertices':'';vm.runInContext(source.replace('R.Puppet={defs,','R.Puppet={test:{getRig,stepPose,bakePose,actorFor,targets,dropRig'+extra+'},defs,'),context);const rig=R.Puppet.test.getRig(R.Puppet.defs[kind]),seen=new Set(),vertexObjects=new Set();let allocations=0;
 const observe=job=>{const v=job.state?.vertices;if(v&&!seen.has(v)){seen.add(v);allocations+=v.reduce((n,a)=>n+a.length,0);for(const a of v)for(const p of a)vertexObjects.add(p);}return v;};
 const step=(job,budget=3)=>{const done=R.Puppet.test.stepPose(job,time+budget);observe(job);return done;};
 const start=key=>{const job={kind,key};assert.equal(step(job,.015),false);assert.ok(job.state.vertices);return job;};
 const finish=job=>{let done=false,i=0;while(!done&&i++<3000){done=step(job);if(!done)assert.ok(!job.rig.library?.has(job.key),'incomplete pose cannot publish');}assert.ok(done);assert.equal(job.state.vertices,null);return job.rig.library.get(job.key);};
 const clean=()=>{R.Bake.touches.length=0;for(const e of rig.library?.values()||[])e.surface.width=e.surface.height=1;rig.library?.clear();};
 return{R,rig,source,context,observe,step,start,finish,run(key){return finish(start(key));},clean,time:()=>time,stats:()=>({canvases,allocatedVertices:allocations,uniqueVertexObjects:vertexObjects.size,snapshots:seen.size}),dispose(){clean();rig.texture.width=rig.texture.height=1;screen.width=screen.height=1;}};
}
function rgba(entry,facing=1){const c=createCanvas(entry.surface.width,entry.surface.height),g=c.getContext('2d');if(facing<0){g.translate(c.width,0);g.scale(-1,1);}g.drawImage(entry.surface,0,0);const out=Buffer.from(g.getImageData(0,0,c.width,c.height).data);c.width=c.height=1;return out;}
function snapshot(e){return{bounds:JSON.parse(JSON.stringify(e.bounds)),scale:e.scale,identity:!!e.identity,pixels:rgba(e)};}
function exact(a,b,label){assert.deepEqual(a.bounds,b.bounds,label+' bounds');assert.equal(a.scale,b.scale,label+' scale');assert.equal(a.identity,b.identity,label+' identity');assert.ok(a.pixels.equals(b.pixels),label+' pixels');}
module.exports={fs,path,assert,root,req,createCanvas,keys,hash,imagesFor,engine,rgba,snapshot,exact};
