'use strict';
// Matched cloud-browser measurements. Strict gates stay 60fps / no >33ms frame / <400ms cold entry.
const fs=require('fs'),path=require('path'),http=require('http'),{chromium}=require('playwright');
const root=path.resolve(process.argv[2]||path.join(__dirname,'..'));
const out=path.resolve(process.argv[3]||path.join(root,'docs/review/v11/performance.json'));
const quick=process.argv.includes('--profile-only'),reportOnly=process.argv.includes('--baseline')||process.argv.includes('--report-only');
const types={'.js':'application/javascript','.css':'text/css','.html':'text/html','.png':'image/png','.jpeg':'image/jpeg','.webp':'image/webp','.ogg':'audio/ogg','.mp3':'audio/mpeg'};
const server=http.createServer((req,res)=>{const pathname=decodeURIComponent(req.url.split('?')[0]),file=path.join(root,pathname==='/'?'index.html':pathname);if(!file.startsWith(root+path.sep)||!fs.existsSync(file)){res.statusCode=404;return res.end();}res.setHeader('Content-Type',types[path.extname(file)]||'application/octet-stream');fs.createReadStream(file).pipe(res);});
const sourceHashes=Object.fromEntries(fs.readdirSync(path.join(root,'js')).filter(f=>f.endsWith('.js')).map(f=>[f,require('crypto').createHash('sha256').update(fs.readFileSync(path.join(root,'js',f))).digest('hex')]));
const baseCommit=require('child_process').execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim();
const workingTreeDirty=!!require('child_process').execFileSync('git',['status','--porcelain','--','js'],{cwd:root,encoding:'utf8'}).trim();
const revisionLabel=workingTreeDirty?'uncommitted working-tree snapshot based on '+baseCommit:baseCommit;
const renderSourceHashes=Object.fromEntries(['stages.js','main.js','art.js','puppets.js','hud.js','fx.js','performance.js','scenes.js'].map(f=>[f,sourceHashes[f]]));
const report={sourceHashes,renderSourceHashes,baseCommit,workingTreeDirty,revisionLabel,method:'Cloud Linux Chromium software Canvas, 1280x720, full effects, AUTO quality=1 held fixed, native RAF. Fresh context for each cold entry, ordinary asset-ready boot. Frame timings include compositor/host scheduling; no Mac or physical-device claim. --profile-only records an additional stage 3 CPU profile; full acceptance windows do not run the CPU sampling profiler.',root,commit:workingTreeDirty?null:baseCommit,cold:[],fights:[],errors:[]};
const stats=a=>{const s=a.slice().sort((a,b)=>a-b);return {p50:s[Math.floor(s.length*.5)]||0,p95:s[Math.floor(s.length*.95)]||0,max:s[s.length-1]||0};};
(async()=>{let browser;try{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{}),args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu','--disable-accelerated-2d-canvas']});report.browser=await browser.version();
 async function open(music){const c=await browser.newContext({viewport:{width:1280,height:720}}),p=await c.newPage();p.on('pageerror',e=>report.errors.push(e.message));p.on('response',r=>{if(r.status()>=400)report.errors.push(r.status()+' '+r.url());});p.on('requestfailed',r=>report.errors.push('requestfailed '+r.url()+' '+r.failure()?.errorText));await p.addInitScript(on=>{localStorage.setItem('rwb-settings',JSON.stringify({music:on?1:0,volume:1,fx:'full',mode:'auto'}));},music);await p.goto('http://127.0.0.1:'+server.address().port+'/');await p.waitForFunction(()=>window.RWB?.assets.done,null,{timeout:120000});const assetReadyMs=await p.evaluate(()=>performance.now());await p.waitForFunction(()=>RWB.game?.scene,null,{timeout:120000});const bootReadyMs=await p.evaluate(()=>performance.now());await p.keyboard.press('Shift');await p.evaluate(()=>{RWB.perf.runtimeLite=false;RWB.perf.quality=1;RWB.display.resize();RWB.perf.observe=()=>{};});return {c,p,assetReadyMs,bootReadyMs,preparationMs:bootReadyMs-assetReadyMs};}
 if(!quick)for(const music of [false,true])for(let level=0;level<5;level++){
  const {c,p,assetReadyMs,bootReadyMs,preparationMs}=await open(music);const row=await p.evaluate(async({level,music})=>{const R=RWB;let seed=1900+level;Math.random=()=>((seed=(seed*1664525+1013904223)>>>0)/4294967296);const start=performance.now();R.game.setSceneNow(new R.scenes.Play(R.game,level,{difficulty:'normal',callandor:level===4}));const initMs=performance.now()-start;await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));return{stage:level+1,music,initMs,enterMs:performance.now()-start,poseMs:R.perf.lastPoseMs,musicStarted:R.audio.trace&&R.audio.trace.slice(-4)};},{level,music});Object.assign(row,{assetReadyMs,bootReadyMs,preparationMs});report.cold.push(row);console.log('COLD',JSON.stringify(row));await c.close();}
 for(const music of (quick?[false]:[false,true]))for(const level of (quick?[2]:[0,2,4])){
  const {c,p,assetReadyMs,bootReadyMs,preparationMs}=await open(music);await p.evaluate(level=>{const R=RWB;let n=0,seed=1900+level;Math.random=()=>((seed=(seed*1664525+1013904223)>>>0)/4294967296);const s=new R.scenes.Play(R.game,level,{wave:3,lives:99,difficulty:'normal',callandor:level===4});R.game.setSceneNow(s);window.sampleScene=s;R.input.beginFrame=()=>{n++;R.input.pressed={};if(n%24===0)R.input.pressed.attack=true;if(n%97===0)R.input.pressed.special=true;if(n%181===0)R.input.pressed.jump=true;s.player.hp=s.player.hpMax;};R.input.axis=()=>{const e=s.enemies.filter(e=>!e.dead).sort((a,b)=>Math.abs(a.x-s.player.x)-Math.abs(b.x-s.player.x))[0];return e?{x:Math.abs(e.x-s.player.x)>45?Math.sign(e.x-s.player.x):0,y:Math.abs(e.y-s.player.y)>8?Math.sign(e.y-s.player.y)*.7:0}:{x:0,y:0};};},level);
  await p.waitForTimeout(2000);
  const client=await c.newCDPSession(p);await client.send('Profiler.enable');await client.send('Profiler.setSamplingInterval',{interval:500});if(level===2&&quick)await client.send('Profiler.start');
  const sample=await p.evaluate(async()=>{const R=RWB,s=sampleScene,costs={},wrap=(o,k,name)=>{if(!o||!o[k])return;const original=o[k];o[k]=function(...args){const t=performance.now();try{return original.apply(this,args);}finally{const row=costs[name]||(costs[name]=[]);row.push(performance.now()-t);}};};for(const [o,k,name] of [[R.StageWorld,'draw','stage.draw'],[R.StageWorld,'near','stage.near'],[R,'drawHUD','hud'],[R.Mashadar&&R.Mashadar.prototype,'draw','mashadar'],[R.FX.prototype,'draw','fx'],[R.Puppet,'draw','puppet'],[s,'update','scene.update'],[s,'draw','scene.draw'],[R.Bake,'pump','bake']])wrap(o,k,name);R.perf.hitches=[];R.perf.work=[];const gaps=[];await new Promise(resolve=>{let last=0,start=0;function tick(t){if(!start)start=t;if(last)gaps.push(t-last);last=t;if(t-start>=10000)resolve();else requestAnimationFrame(tick);}requestAnimationFrame(tick);});return{gaps,costs,work:R.perf.work,hitches:R.perf.hitches,outside:R.perf.outside,poseFallbacks:R.perf.poseFallbacks,queue:R.Bake.q.map(j=>j.name)};});
  if(level===2&&quick){const result=await client.send('Profiler.stop');const profile=out.replace(/\.json$/,`-stage3-${music?'music-on':'music-off'}.cpuprofile`);fs.mkdirSync(path.dirname(profile),{recursive:true});fs.writeFileSync(profile,JSON.stringify(result.profile));}
  const fps=sample.gaps.length*1000/sample.gaps.reduce((a,b)=>a+b,0),over33=sample.gaps.filter(n=>n>33).length,row={stage:level+1,music,assetReadyMs,bootReadyMs,preparationMs,frames:sample.gaps.length,fps,over33,gapsMs:stats(sample.gaps),costs:Object.fromEntries(Object.entries(sample.costs).map(([k,a])=>[k,{calls:a.length,...stats(a),sum:a.reduce((x,y)=>x+y,0)}])),raw:sample};report.fights.push(row);console.log('FIGHT',JSON.stringify({...row,raw:undefined}));await c.close();
 }
 report.gates={cold:quick?null:report.cold.length===10&&report.cold.every(r=>r.enterMs<400),fights:report.fights.length===(quick?1:6)&&report.fights.every(r=>r.fps>=59.5&&r.over33===0),errors:report.errors.length===0};report.reportOnly=reportOnly;report.profileOnly=quick;
 if(!reportOnly&&Object.values(report.gates).some(v=>v===false))process.exitCode=1;
}catch(error){report.errors.push(String(error.stack||error));process.exitCode=1;}finally{if(browser)await browser.close();server.close();fs.mkdirSync(path.dirname(out),{recursive:true});fs.writeFileSync(out,JSON.stringify(report,null,2)+'\n');console.log('Saved '+out);}})().catch(e=>{console.error(e);process.exitCode=1;});
