'use strict';
const assert = require('assert/strict'), path = require('path');
const { boot } = require('./soak.cjs');
const R = boot(path.resolve(__dirname, '..'));
let passed = 0;
const check = (ok, name) => { assert.ok(ok, name); passed++; console.log('PASS ' + name); };
const input = pressed => ({ pressed: pressed || {}, held: {}, axis: () => ({ x: 0, y: 0 }) });
const old = R.settings.validateRun({ level: 4, wave: 5, score: 1500, extra: { callandor: true, lives: 2 } });
check(old.extra.difficulty === 'normal' && old.extra.callandor && old.extra.lives === 2, 'Legacy saves keep their state and use Normal');
R.settings.set({ difficulty: 'hard' });
const legacy = R.resumeRun(R.game, old);
check(legacy.difficulty === 'normal', 'Continue does not adopt the changed next-run difficulty');
const hard = new R.scenes.Play(R.game, 1, {});
check(hard.difficulty === 'hard', 'A new run uses the chosen Hard setting');
check(hard.checkpointExtra().difficulty === 'hard' && hard.carryToNext().difficulty === 'hard', 'Hard persists in checkpoints and between stages');
const switched = [], game = { setScene: scene => switched.push(scene) };
hard.game = game; hard.restartStage();
check(switched.pop().difficulty === 'hard', 'Restart preserves the active difficulty');
R.settings.set({ difficulty: 'normal' });
const final = new R.scenes.Play(R.game, 4, { callandor: true });
let reel = final.nextStage();
check(reel instanceof R.scenes.Reel && reel.lines === R.CAPTIONS.escape, 'Taim clear routes to escape before homecoming');
check(R.CAPTIONS.escape.length === 3 && R.CAPTIONS.escape.every(l => R.storyArt(l.id) === 'cut-escape'), 'Escape has three catalogued painted story beats');
check(R.CAPTIONS.stage4.every(l => R.storyArt(l.id) === 'cut-stage4'), 'Stone of Tear arrival does not show Callandor already acquired');
check(R.CAPTIONS.callandor.every(l => R.storyArt(l.id) === 'cut-callandor'), 'Post-victory Callandor reveal has its own acquisition painting');
check(R.CAPTIONS.stage5.every(l => R.storyArt(l.id) === 'cut-stage5-arrival'), 'Black Tower arrival does not show Twinkle Toes already rescued');
check(['taim_phase_03', 'st5_kenzie_03', 'st5_kenzie_01', 'st5_riley_02', 'st5_kenzie_02'].every(id => R.storyArt(id) === 'cut-stage5-finale'), 'Freed/finale lines retain the joint-finish painting');
let nextCount = 0, after;
reel.game = { setScene: s => { nextCount++; after = s; } };
for (let i = 0; i < 6; i++) reel.advance();
check(nextCount === 1 && after.lines === R.CAPTIONS.ending, 'Repeated escape NEXT advances to homecoming exactly once');
after.game = { setScene: s => { nextCount++; reel = s; } };
for (let i = 0; i < 6; i++) after.advance();
check(nextCount === 2 && reel instanceof R.scenes.Victory, 'Homecoming advances to family credits exactly once');
let exits = 0; reel.game = { setScene: () => exits++ };
reel.update(12, input());
check(exits === 0, 'Family credits remain readable until the player chooses to leave');
reel.update(1 / 60, input({ click: true })); reel.update(1 / 60, input({ start: true }));
check(exits === 1, 'Keyboard and tap exit credits without duplicate transitions');
let menu;
const menuGame = { setScene: scene => { menu = scene; } };
const title = new R.scenes.Title(menuGame);
title.selection = title.items().indexOf('OPTIONS'); title.update(1 / 60, input({ start: true }));
menu.panel.sel = menu.panel.rows.length - 1;
menu.update(1 / 60, input({ start: true }));
check(menu instanceof R.scenes.Title, 'Options BACK works with keyboard/gamepad confirmation');
title.update(1 / 60, input({ start: true }));
const point = { x: 200, y: menu.panel.y0 + (menu.panel.rows.length - 1) * menu.panel.step };
menu.update(1 / 60, { ...input({ click: true }), pointer: point });
check(menu instanceof R.scenes.Title, 'Options BACK works with a pointer/touch row tap');
const { createCanvas } = require('@napi-rs/canvas'), ctx = createCanvas(640, 360).getContext('2d');
for (let stage = 0; stage < 5; stage++) {
  const s = new R.scenes.Play(R.game, stage, { wave: 5 });
  s.draw(ctx);
}
check(true, 'All five boss introductions render even when paintings are unavailable');
const r = new R.scenes.Reel(R.game, R.CAPTIONS.escape, () => new R.scenes.Title(R.game), 'ESCAPE FROM THE BLACK TOWER');
r.draw(ctx); new R.scenes.Victory(R.game).draw(ctx);
check(true, 'Escape and credits retain playable missing-art fallbacks');
console.log(passed + ' release checks passed.');
