'use strict';
// Exercise the real main loop and DOM input without paying for draw work in
// timing-only cases. review.cjs and performance.cjs cover the actual renderer.
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),server=http.createServer((req,res)=>{const file=path.join(root,req.url.split('?')[0]==='/'?'index.html':req.url.split('?')[0]);if(!file.startsWith(root+path.sep)||!fs.existsSync(file)){res.statusCode=404;return res.end();}res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.html')?'text/html':file.endsWith('.css')?'text/css':'application/octet-stream');fs.createReadStream(file).pipe(res);});
(async()=>{let browser;try{await new Promise(r=>server.listen(0,'127.0.0.1',r));browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});const p=await browser.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(()=>{window.requestAnimationFrame=cb=>(window.gameFrame=cb,1);const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){const ctx=original.call(this,type,...args);if(type==='webgl')window.meshGL=ctx;return ctx;};});await p.goto('http://127.0.0.1:'+server.address().port);await p.waitForFunction(()=>RWB.assets.done,{},{polling:100});await p.evaluate(async()=>{await RWB.prepareRendering();window.now=performance.now();window.emptyFight=()=>{const R=RWB,s=new R.scenes.Play(R.game,0,{});s.enemies=[];s.props=[];s.hazards=[];s.pickups=[];s.finishWave=()=>{};s.draw=()=>{};R.game.setSceneNow(s);R.game.fadeDir=0;R.game.fade=0;R.input.clear();gameFrame(now+=100);return s;};});
 const refresh=[];for(const hz of [60,120,144]){await p.evaluate(()=>{window.s=emptyFight();window.startX=s.player.x;});await p.keyboard.down('d');const row=await p.evaluate(hz=>{for(let i=0;i<hz;i++)gameFrame(now+=1000/hz);return {hz,distance:s.player.x-startX,state:s.player.state};},hz);refresh.push(row);await p.keyboard.up('d');}
 assert.ok(refresh.every(r=>Math.abs(r.distance-refresh[0].distance)<1e-7));assert.ok(refresh[0].distance>100);
 await p.evaluate(()=>{window.s=emptyFight();window.kicks=0;const begin=s.player.beginMove.bind(s.player);s.player.beginMove=(...a)=>{kicks++;return begin(...a);};});await p.keyboard.press('j');const buffered=await p.evaluate(()=>{gameFrame(now+=1000/240);const before=kicks;gameFrame(now+=1000/240);gameFrame(now+=1000/120);for(let i=0;i<5;i++)gameFrame(now+=1000/120);return {before,after:kicks};});assert.equal(buffered.before,0);assert.equal(buffered.after,1);
 await p.keyboard.down('d');const focus=await p.evaluate(()=>{window.dispatchEvent(new Event('blur'));const x=s.player.x;gameFrame(now+=10000);return {paused:s.paused,held:!!RWB.input.held.right,moved:s.player.x-x};});await p.keyboard.up('d');assert.deepEqual(focus,{paused:true,held:false,moved:0});
 const resize=await p.evaluate(async()=>{RWB.display.setMode('auto');RWB.perf.coarse=true;Object.defineProperty(window,'devicePixelRatio',{configurable:true,value:3});RWB.display.resize();const auto=document.getElementById('game').width;RWB.display.setMode('sharp');const sharp=document.getElementById('game').width;for(let i=0;i<25;i++)window.dispatchEvent(new Event('resize'));await new Promise(r=>setTimeout(r,80));return {auto,sharp,afterBurst:document.getElementById('game').width};});assert.ok(resize.auto<=1280&&resize.sharp>resize.auto&&resize.afterBurst===resize.sharp);
 const mesh=await p.evaluate(()=>{
   const R=RWB,c=document.createElement('canvas');c.width=c.height=512;const g=c.getContext('2d'),scene=new R.scenes.Play(R.game,0,{}),a=new R.Trolloc(scene,128,200,'axe');a.state='walk';a.visualHeight=112;R.Puppet.updateGait(a,1/60);for(let i=0;i<20;i++){a.x+=2;R.Puppet.updateGait(a,1/60);}
   const render=canvas=>{R.perf.canvasSkin=canvas;g.clearRect(0,0,512,512);g.setTransform(2,0,0,2,0,0);R.Puppet.draw(g,a,0,'trolloc');g.setTransform(1,0,0,1,0,0);return g.getImageData(0,0,512,512).data;};
   const gpu=render(false),cpu=render(true);let opaque=0,missing=0,error=0,pixels=0;for(let i=0;i<gpu.length;i+=4){if(cpu[i+3]>200){opaque++;if(gpu[i+3]<100)missing++;}if(cpu[i+3]>200&&gpu[i+3]>200){error+=Math.abs(cpu[i]-gpu[i])+Math.abs(cpu[i+1]-gpu[i+1])+Math.abs(cpu[i+2]-gpu[i+2]);pixels++;}}
   R.perf.canvasSkin=false;return {webgl:!!window.meshGL,opaque,missing,missingFraction:missing/opaque,meanOpaqueChannelError:error/(pixels*3)};
 });assert.ok(mesh.webgl&&mesh.missingFraction<.02&&mesh.meanOpaqueChannelError<8);
 const loss=await p.evaluate(async()=>{const ext=window.meshGL.getExtension('WEBGL_lose_context');ext.loseContext();await new Promise(r=>setTimeout(r,40));const c=document.createElement('canvas');c.width=c.height=300;const g=c.getContext('2d');const ok=RWB.Puppet.draw(g,{x:140,y:200,z:0,state:'hurt',stateT:.2,facing:1},0,'trolloc');const data=g.getImageData(0,0,300,300).data;return {contextLost:window.meshGL.isContextLost(),painted:ok&&data.some((v,i)=>i%4===3&&v>200)};});assert.deepEqual(loss,{contextLost:true,painted:true});
 assert.deepEqual(errors,[]);const report={errors,refresh,buffered,focus,resize,mesh,loss,notes:'Real main loop and keyboard events, synthetic display timestamps. Scene draw skipped only for timing/input cases; separate browser review and performance reports exercise painted rendering.'};fs.writeFileSync(path.join(root,'docs/review/smoothness-browser.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));
 }finally{if(browser)await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
