'use strict';
const assert=require('node:assert/strict'),{boot}=require('./soak.cjs'),path=require('node:path');
const R=boot(path.resolve(__dirname,'..')),input={pressed:{},held:{},axis:()=>({x:1,y:0})},checks=[];
function test(name,run){run();checks.push(name);console.log('PASS '+name);}
test('60, 120 and 144 Hz displays produce identical 60 Hz simulation distance',()=>{for(const hz of [60,120,144]){const clock=new R.FrameClock();let distance=0,ticks=0;for(let n=0;n<hz*10;n++)clock.advance(1/hz,input,dt=>{distance+=120*dt;ticks++;});assert.equal(ticks,600);assert.equal(distance,1200);}});
test('A press between ticks survives and is consumed once across catch-up ticks',()=>{const clock=new R.FrameClock();let hits=0;clock.advance(1/240,{...input,pressed:{attack:true}},()=>{throw Error('early tick');});clock.advance(1/120,input,()=>{throw Error('early tick');});clock.advance(.05,input,(dt,i)=>{if(i.pressed.attack)hits++;});assert.equal(hits,1);clock.advance(.05,input,(dt,i)=>{if(i.pressed.attack)hits++;});assert.equal(hits,1);});
test('Long stalls have a five-tick catch-up bound; resetting clears stale input/time',()=>{const clock=new R.FrameClock();assert.equal(clock.advance(12,input,()=>{}),5);assert.ok(clock.dropped>0);clock.advance(.001,{...input,pressed:{attack:true}},()=>{});clock.reset();let hits=0;clock.advance(1/60,input,(dt,i)=>hits+=!!i.pressed.attack);assert.equal(hits,0);assert.ok(clock.accumulator<1e-8);});
test('Render interpolation restores authoritative actor, gait, camera and projectile values',()=>{const scene={camera:{x:0,punchX:4},player:{x:10,y:270,z:0,walkDistance:4,gait:{x:10,y:270,phase:1,feet:[{x:15,y:270,lift:0}]}},projectiles:[{x:20,y:260,z:20}]};R.Motion.capture(scene);scene.player.x=14;scene.player.gait.phase=1.1;scene.camera.x=8;scene.projectiles[0].x=28;const saved=JSON.stringify(scene);R.Motion.alpha=.5;R.Motion.apply(scene);assert.equal(scene.player.x,12);assert.equal(scene.camera.x,4);assert.equal(scene.projectiles[0].x,24);assert.equal(scene.player.gait.phase,1.05);R.Motion.restore(scene);assert.equal(scene.player.x,14);assert.equal(scene.camera.x,8);assert.equal(scene.player.gait.phase,1.1);assert.equal(scene.projectiles[0].x,28);R.Motion.alpha=1;});
test('Teleports and paused scenes do not interpolate across arenas',()=>{const scene={camera:{x:0},player:{x:10,y:270}};R.Motion.capture(scene);scene.player.x=500;R.Motion.alpha=.5;R.Motion.apply(scene);assert.equal(scene.player.x,500);R.Motion.restore(scene);scene.paused=true;scene.player.x=12;R.Motion.apply(scene);assert.equal(scene.player.x,12);R.Motion.alpha=1;});
test('Camera follow and punch damping agree at 60 and 120 updates/second',()=>{const values=[60,120].map(hz=>{const c=new R.Camera({length:3000});c.punch(1,12,4);for(let n=0;n<hz;n++){c.follow(1200,1/hz);c.update(1/hz);}return [c.x,c.punchX];});for(let i=0;i<2;i++)assert.ok(Math.abs(values[0][i]-values[1][i])<1e-8);});
test('A repeated light hit does not extend hit-stop; big finish remains available',()=>{const c=new R.Camera();c.impact(1,'light');assert.equal(c.hitstop,.025);c.update(1/60);const remaining=c.hitstop;c.impact(1,'light');assert.equal(c.hitstop,remaining);c.impact(1,'super');assert.equal(c.hitstop,.14);});
test('AUTO adapts after sustained overload, recovers gradually and leaves SHARP alone',()=>{const resize=R.display.resize;let changes=0;R.display.resize=()=>changes++;R.display.mode='auto';R.perf.quality=1;R.perf.slow=R.perf.fast=0;for(let i=0;i<90;i++)R.perf.observe(25,1/60,true);assert.equal(R.perf.quality,.85);assert.equal(changes,1);for(let i=0;i<500;i++)R.perf.observe(5,1/60,true);assert.equal(R.perf.quality,.95);R.display.mode='sharp';for(let i=0;i<180;i++)R.perf.observe(50,1/30,true);assert.equal(R.perf.quality,.95);R.display.mode='auto';R.perf.quality=1;R.perf.runtimeLite=false;R.display.resize=resize;});
test('Focus reset releases held keyboard, gamepad and touch state',()=>{R.input.held.right=true;R.input.pressed.attack=true;R.input.touch.joy.active=true;R.input.gamepad.x=1;R.input.clear();assert.equal(R.input.axis().x,0);assert.ok(!R.input.held.right&&!R.input.pressed.attack&&!R.input.touch.joy.active);});
console.log(checks.length+' smoothness checks passed.');
